huff-language/huff-rs

huff_core/src/lib.rs, huff_core/tests/erc20.rs, huff_core/tests/erc721.rs, huff_core/tests/recurse_deps.rs, huff_core/tests/sources.rs, huff_utils/src/error.rs, huff_utils/src/io.rs
This PR properly bubbles up file fetching errors instead of gracefully allowing `0` files to compile.
Effect (the first run is the original `huffc` output, second is the output created by this pr):
=> fix(huff_core): Missing File Erroring

huff_core/src/lib.rs, huff_core/tests/errors.rs, huff_core/tests/gen_artifact.rs
As detailed in #126 , `huffc` errors when there is no `CONSTRUCTOR` macro defined. This should not be the behavior when no constructor inputs are passed. `huffc` should produce valid bytecode when there is no constructor present and fail in this case if constructor inputs are still provided.
=> fix(huff_core): Allow Missing Constructor

huff_cli/src/huffc.rs, huff_core/src/lib.rs, huff_utils/src/artifact.rs, huff_utils/src/files.rs
Introduces a new `-a` (`--artifacts` longhand) flag to enable artifact output.
Even if the output directory or output location is specified by the respective `-o` and `-d` flags, if the artifacts flag is not added, `huffc` will **not** export anything.
closes #127
=> fix(huff_core): Artifact Exports Off By Default

Cargo.lock, huff_cli/Cargo.toml, huff_cli/src/huffc.rs
Prevents piped output from including the `Compiling` spinner.
closes #133
=> fix(huff_cli): Only output a spinner if stdout is a TTY

.github/workflows/release.yaml
Changes the release workflow to build the nightly release off of the `stage` branch.
=> fix(workflow): Build nightly on `stage` branch

Cargo.lock, huff_core/Cargo.toml, huff_core/tests/codegen_errors.rs, huff_core/tests/errors.rs, huff_core/tests/parser_errors.rs, huff_lexer/src/lib.rs, huff_lexer/tests/keywords.rs, huff_parser/src/lib.rs, huff_utils/src/abi.rs, huff_utils/src/ast.rs, huff_utils/src/error.rs, huff_utils/src/files.rs, huff_utils/tests/files.rs
`import.huff`
```huff
#define macro SOME_RANDOM_MACRO() = takes(2) returns (1) {
// Store the keys in memory
dup1 0x00 mstore
swap1 dup1 0x00 mstore
// Hash the data, generating a key.
0x40 sha3
}
```
`error.huff`
```huff
#include "./import.huff"
#define function addressGetter() internal returns (address)
```
**Prior to these fixes**, compiling `error.huff` produced the error:
**Now**, with this pr's source segment fixes, propagation, and hints, the error produced is:
=> fix(errors): Propagation

README.md
> Please provide a short description here and review the requirements below.
I was having probs removing the old huffc npm package and didnt even realize it at first because it seemed to take when i ran `yarn global remove huffc` and also i didnt know what version we were on or that the --help files look different now.  Finally after some headbanging I realized i was still running the old version and went back and tried removing it again but with `sudo` this time, and that worked.
Thought I'd add something in the docs here to help others in case they have a similar experience.
=> docs: add steps to remove old version of huffc

huff_cli/src/huffc.rs, huff_utils/src/abi.rs, huff_utils/src/ast.rs, huff_utils/src/lib.rs, huff_utils/src/sol_interface.rs
Adds a new flag to the CLI (`-g, --interface`) to generate a solidity interface for a Huff contract.
=> feat(huff_cli): Solidity interface generation

huff_cli/src/huffc.rs, huff_codegen/tests/constructor_args.rs, huff_core/README.md, huff_core/src/cache.rs, huff_core/src/lib.rs, huff_core/tests/file_resolution.rs, huff_core/tests/gen_artifact.rs, huff_utils/src/types.rs
Artifact caching wasn't taking into account different constructor arguments, resulting in erroneous bytecode output.
✅ [Tested] Additionally fixes constructor arg non-interactive array inputs. ie `100, 200` would error as a constructor arg input since there were no surrounding brackets.
=> fix: Bad Artifact Caching

huff_lexer/src/lib.rs, huff_lexer/tests/labels.rs
I ran into an interesting edge case today when naming a jump label `return_uint`. Because of the way opcodes are parsed, attempting to push this label to the stack mistakenly gets parsed as a `return` opcode. This small change handles this case by including underscores when peeking for an opcode.
=> fix(huff_lexer): opcode lexing bug

huff_cli/src/huffc.rs, huff_codegen/README.md, huff_codegen/src/irgen/arg_calls.rs, huff_codegen/src/irgen/constants.rs, huff_codegen/tests/abigen.rs, huff_core/README.md, huff_core/src/lib.rs, huff_core/tests/file_resolution.rs, huff_core/tests/gen_artifact.rs, huff_parser/README.md, huff_parser/src/lib.rs, huff_parser/tests/constant.rs, huff_parser/tests/storage_pointer_derivation.rs, huff_utils/src/abi.rs, huff_utils/src/ast.rs
Adds the ability to override / set new constant definitions for the current compilation environment via the `-c` flag in the CLI.
`huffc ./Test.huff -b -c a=0x01 b=0xa57b`
=> feat(huff_cli): Constant Overrides

Cargo.lock, huff_parser/src/lib.rs, huff_parser/tests/imports.rs
The `huff_parser` previously incorrectly expected imports to be defined _before_ any definitions. While this works for conventional file structures, scrambled code created by useful libraries like [foundry-huff](https://github.com/huff-language/foundry-huff) break this convention by combining code in an unstructured manner. This means imports are scrambled throughout the file.
Thus, this patch allows the `#define` and `#include` keywords to be gracefully used in any order throughout huff files.
=> fix: Scrambled Imports

huff_utils/src/ast.rs
Reverts some changes to hotfix `try_from` panicking in the latest nightly build
=> fix(huff_utils): Ast `try_from` panics

huff_parser/src/lib.rs, huff_parser/tests/labels.rs
Fixes the parser not recognizing builtin function calls underneath jumplabels.
=> Fix builtins under jumplabels

huff_parser/src/lib.rs, huff_parser/tests/breaking_param_invocation.rs
Previously, passing an unacceptable token as a parameter to a macro would cause the parser to loop indefinitely as it tried to find a closing parenthesis.
This pr introduces a check in parameter parsing that makes sure some sort of parameter was parsed (type or name), otherwise we have an invalid token.
Closes #178
=> fix: Invalid Parameter Types

huff_cli/src/huffc.rs, huff_codegen/tests/abigen.rs, huff_parser/src/lib.rs, huff_parser/tests/error.rs, huff_utils/src/abi.rs, huff_utils/src/ast.rs, huff_utils/src/sol_interface.rs
Allows the user to specify an optional string to the `-g` huff_cli flag.
Closes #165
`huffc File.huff` -> Doesn't produce an interface.
`huffc File.huff -g` -> Outputs an `IFile.sol` interface.
`huffc File.huff -g MyInterface` -> Creates a `MyInterface.sol` interface.
=> feat: Interface Overloading

huff_codegen/src/irgen/statements.rs, huff_core/tests/builtins.rs, huff_lexer/tests/builtins.rs, huff_parser/src/lib.rs, huff_parser/tests/labels.rs, huff_utils/src/ast.rs
Adds a new builtin, `__RIGHTPAD(n)` to assist with pushing right-padded bytes to the stack.
```
#define macro MAIN() = takes (0) returns (0) {
// a57b000000000000000000000000000000000000000000000000000000000000
__RIGHTPAD(0xa57b) 
// 48656c6c6f2c20576f726c642100000000000000000000000000000000000000
__RIGHTPAD(0x48656c6c6f2c20576f726c6421)
// 06d6f6f736500000000000000000000000000000000000000000000000000000
__RIGHTPAD(0x06d6f6f7365)
}
```
closes #184
=> feat(huff_codegen): `__RIGHTPAD` builtin

huff_codegen/src/irgen/arg_calls.rs, huff_core/src/cache.rs, huff_core/tests/macro_invoc_args.rs, huff_parser/tests/macro.rs, huff_utils/src/evm.rs
Fixes failing to parse idents in macro invocations as opcodes.
For example, invoking a macro with an opcode like: `MYMACRO(returndatasize)` would fail to compile since the `returndatasize` ident was parsed as a label instead of as an opcode.
Also fixes the `Opcode::from(&str)` impl by strum. Note: In another pr we should move away from the custom maps from opcode enum  variants to string and use this new strum impl.
=> fix: Opcodes in Macro Invocations

huff_codegen/src/irgen/arg_calls.rs, huff_core/src/cache.rs, huff_core/tests/macro_invoc_args.rs, huff_core/tests/parser_errors.rs, huff_parser/tests/macro.rs, huff_utils/src/evm.rs
Fixes an issue where constants weren't recognized if passed as a macro argument.
Branches off of #188, merge after that one.
=> fix(huff_codegen): Constants as Macro Args

huff_cli/README.md, huff_cli/src/huffc.rs
We added a new `huffc` flag `-r` or `--bin-runtime` that would only print the runtime bytecode.
=> feat(huff_cli): new runtime bytecode flag is added.

huff_parser/src/lib.rs, huff_parser/tests/macro.rs
Adds support for optional takes / returns for macros by using `.map_or`, defaulting to 0.
Fixes #192
=> feat(huff_parser): macro optional takes/returns

Cargo.lock, foundry.toml, huff_core/benches/huff_benchmark.rs, huff_core/src/lib.rs, huff_core/tests/aliased_imports.rs, huff_core/tests/erc20.rs, huff_core/tests/erc721.rs, huff_core/tests/recurse_deps.rs, huff_parser/src/lib.rs, huff_parser/tests/imports.rs, huff_utils/Cargo.toml, huff_utils/src/files.rs, huff_utils/tests/files.rs
Tackles #187 
Adds remapping support for import resolutions. So a remapping in a foundry.toml can be supported when compiling huff contracts. For example, a remapping for huffmate like `huffmate/=lib/huffmate/src/` located in a `foundry.toml` file can be successfully parsed by the huff compiler. This allows you to import huffmate contracts inside a huff contract using `foundry.toml` remappings (WLOG)
Note: This PR rips out file path validation logic in the parser since files are validated and fully flattened at the compiler top-level.
=> feat(huff_core): Remapping Import Resolution

huff_utils/src/evm.rs
Low hanging fruit: Addresses #209 Introduction of Prevrandao opcode
```
#define macro MAIN() = {
prevrandao
}
```
Bytecode yields expected value with above test file:
```
cargo run --release test.huff --bytecode
Finished release [optimized + debuginfo] target(s) in 0.32s
Running `target/release/huffc test.huff --bytecode`
⠙ Compiling... 
60018060093d393df344
```
Runtime yields expected value
```
cargo run --release test.huff --bin-runtime
Finished release [optimized + debuginfo] target(s) in 0.16s
Running `target/release/huffc test.huff --bin-runtime`
⠙ Compiling... 
44
```
=> feat(evm): Add prevrandao

huff_codegen/src/irgen/statements.rs, huff_codegen/src/lib.rs, huff_core/tests/push_overrides.rs, huff_parser/src/lib.rs, huff_parser/tests/opcodes.rs, huff_tests/src/runner.rs, huff_utils/src/ast.rs, huff_utils/src/bytes_util.rs, huff_utils/src/error.rs, huff_utils/src/evm.rs
=> various fixes and features

huff_codegen/src/irgen/statements.rs, huff_core/tests/free_storage_pointer.rs, huff_core/tests/macro_invoc_args.rs, huff_core/tests/parser_errors.rs, huff_lexer/tests/imports.rs, huff_parser/src/lib.rs, huff_parser/tests/opcodes.rs, huff_utils/src/ast.rs
=> fix: free storage pointer used in param bug

.github/workflows/release.yaml
When running `huffup` on ubutnu 20.04 (focal) it results in a  `GLIBC_2.34' not found` error. This error is quite hard to appease as upgrading glibc is quite a task that various forums do not recommend. However after installing a ubuntu 22.~ release and running huffup the issue disappears.  
I think the error is occuring as the build system currently runs on `ububtu-latest` which is no longer 20.04 but 22. Such it is compiling with a version of glibc that is not available to ubuntu 20.04 without a risky upgrade path.
This pr locks the build system to use 20.04 which should unblock users who are encountering this issue.
=> chore: lock ubuntu 20.04 in release.yml

huff_utils/src/files.rs, huff_utils/tests/files.rs
When the parent path doesn't start with a `./` or `../` and the child starts with a `../` the calculated path is incorrect.
e.g.
```rust
files::FileSource::localize_file("examples/ERC20.huff", "../random_dir/Address.huff")
// returns    "../examples/random_dir/Address.huff"
// expected   "./random_dir/Address.huff"
```
Fixed by checking if parent starts with a `.` and if not prefixing it with one.
Added a regression test.
=> fix(huff_utils) incorrect path localization

huff_cli/README.md
The link to clap's derive feature in the huff_cli readme was broken so I updated it to reference the docs. But if there is a better place to link to I can use that instead!
=> fix: broken link to clap's derive feature in cli README

huff_codegen/src/irgen/statements.rs, huff_core/tests/verbatim.rs, huff_utils/src/ast.rs, huff_utils/src/error.rs
Implements a `__VERBATIM` builtin that allows developers to inline whatever hex they would like. This is opens the door to test out opcodes that may not already be supported by huff or do some mad stuff like placing code tables in the middle of runtime (idk go wild).
Despite there being multiple users who have requested this feature (including issue #225); half of me feels like it may be more harm than good as it opens up ways for people to shoot themselves in the foot. Especially since the way the language has been implemented makes adding opcodes trivial ( it can take as little as 5 minutes ). 
On the other hand, I do feel like it is inline with the Huff ethos to allow the developer to to whatever they would like with their contracts.
That being said, I think it is worth having a …
=> feat: __VERBATIM

huff_lexer/tests/arg_calls.rs, huff_lexer/tests/builtins.rs, huff_lexer/tests/comments.rs, huff_lexer/tests/decorators.rs, huff_lexer/tests/eof.rs, huff_lexer/tests/fsp.rs, huff_lexer/tests/function_type.rs, huff_lexer/tests/hex.rs, huff_lexer/tests/imports.rs, huff_lexer/tests/keywords.rs, huff_lexer/tests/numbers.rs, huff_lexer/tests/symbols.rs, huff_parser/src/lib.rs, huff_parser/tests/event.rs, huff_parser/tests/function.rs, huff_parser/tests/macro.rs, huff_utils/src/abi.rs, huff_utils/src/ast.rs
A clippy update has added a lint for ambiguous exports, where two modules export an entity with the same name. In this case, `Function` and `Event` were both exported from `ast.rs` and `abi.rs`. 
To resolve the issue I have renamed to ast items to be appended with `Definition`, lining up with naming of `TableDefinition` etc seen elsewhere within the module.
=> chore(clippy): resolve ambiguous exports

huff_codegen/src/irgen/arg_calls.rs, huff_codegen/src/irgen/constants.rs, huff_codegen/src/irgen/statements.rs, huff_codegen/src/lib.rs, huff_tests/src/runner.rs, huff_utils/src/ast.rs, huff_utils/src/bytecode.rs
Removed a lot of expensive cloning in favour of passing references in the codegen phase. I tried to do this with minimal refactoring. 
Codegen is about 75% faster now for the erc20 benchmark.
Thanks for @jimjbrettj for introducing my to Huff, this has been fun and educational. 
Before: 
After:
=> Make Codegen Faster Through Less Allocations

huff_codegen/src/irgen/arg_calls.rs, huff_core/tests/macro_invoc_args.rs
=> Use name from parent instead of own arg name for bubbled argcall resolution - fixes #263

huff_cli/src/huffc.rs
Prints the `--help` subcommand output when no arguments provided to the `huff-rs` binary.
=> Print `--help` when no arguments provided

huff_utils/src/evm.rs
This PR introduces a new opcode (MCOPY) introduced in [`EIP-5656`](https://eips.ethereum.org/EIPS/eip-5656).
The changes needed seem to be minimal (just added a new variant to the `Opcode` enum in `evm.rs`, so that the parser/bytecodegen will be able to understand the new opcode), but it was a good way to get acquainted with the codebase.
I'd like to add a small test, something as simple as compiling:
``` 
#define macro MAIN() = {
0x00
0x00
0x20
mcopy
}
```
which becomes `5f5f6020205e`, but I couldn't find the right place to put it (and maybe it's not necessary for such a trivial change).
Anyway, I look forward to your recommendations & corrections, so please, feel free to leave any comments you may have :smiley:
=> MCOPY opcode (EIP-5656)

huff_codegen/src/lib.rs, huff_lexer/tests/builtins.rs, huff_lexer/tests/comments.rs, huff_lexer/tests/context.rs, huff_lexer/tests/decorators.rs, huff_lexer/tests/eof.rs, huff_lexer/tests/evm_types.rs, huff_lexer/tests/fsp.rs, huff_lexer/tests/function_type.rs, huff_lexer/tests/hex.rs, huff_parser/tests/abi.rs, huff_utils/src/ast.rs
=> chore(clippy): appease

huff_lexer/README.md
remove typo in code example to make it compilable
=> fix(docs): typo in code example

huff_parser/src/lib.rs, huff_utils/src/ast.rs, huff_utils/src/error.rs
=> fix: allow index into AstSpan
