huff-language/huff-rs

huff_core/benches/huff_benchmark.rs

Fixes benchmarks; Changes introduced in #121 broke them

fix(benchmarks): Fix benchmarks in accordance w/ #121

---

huff_utils/src/files.rs

fix(huff_utils): Make clippy happy :sweat_smile:

---

README.md

Fixes the huffup installation url.

fix(readme): Huffup Install URL

---

huff_core/src/cache.rs
huff_lexer/src/lib.rs

Fixes clippy errors, toolchain updated.

Fix clippy errors

---

huff_core/tests/erc20.rs
huff_lexer/src/lib.rs

satisfy the nightly clappy gods

---

.github/workflows/docker-publish.yaml

Checks out stage branch if nightly release for docker release job.

fix: Nightly Docker Release

---

huff_core/tests/parser_errors.rs
huff_parser/src/lib.rs
huff_utils/src/evm.rs

Adds the missing `basefee` opcode

fix(huff_utils): `basefee` opcode

---

huff_codegen/tests/abigen.rs
huff_parser/src/lib.rs
huff_parser/tests/error.rs
huff_utils/src/abi.rs
huff_utils/src/ast.rs
huff_utils/src/sol_interface.rs

Adds custom `error` definitions to the solidity interface generation util.

feat(huff_cli): Add custom errors to solidity interface gen

---

huff_core/src/cache.rs

Clippy updated on the nightly toolchain since last night's workflows on #185

fix: Appease the clippy gods

---

Cargo.lock
README.md
huff_cli/Cargo.toml
huff_cli/README.md
huff_codegen/Cargo.toml
huff_core/Cargo.toml
huff_lexer/Cargo.toml
huff_parser/Cargo.toml
huff_utils/Cargo.toml
huffup/README.md

Bumps crate versions to `0.3.0` and some other minor metadata changes 📦

fix: Stable Version Bumps

---

huff_codegen/src/lib.rs
huff_codegen/tests/churn.rs

feat: custom bootstrap code

---

Cargo.lock
huff_codegen/README.md
huff_codegen/src/irgen/arg_calls.rs
huff_codegen/src/irgen/constants.rs
huff_codegen/src/lib.rs
huff_codegen/tests/abigen.rs
huff_core/src/lib.rs
huff_lexer/src/lib.rs
huff_parser/README.md
huff_parser/src/lib.rs
huff_parser/tests/constant.rs
huff_parser/tests/storage_pointer_derivation.rs
huff_utils/src/abi.rs
huff_utils/src/ast.rs
huff_utils/src/error.rs

Parallelizes lexing and parsing of file sources using `into_par_iter()` and thread-safe smart pointers `Arc<Mutex<?>>` as opposed to `Rc<Refcell<?>>` for contract definitions.

feat: Enhance Parallelization

---

huff_codegen/src/irgen/statements.rs
huff_parser/tests/error.rs

Fixing https://github.com/huff-language/huff-rs/issues/212

fix(huff-codegen) use error selector instead of name

---

huff_utils/src/files.rs

fix: clippy

---

huffup/huffup

Fix #227 (see the issue for more details)

fix(huffup): symlink

---

Dockerfile

Fixes failing dockerfile, replacing it with one that uses cargo chef

fix: update dockerfile and use caching

---

Cargo.lock
README.md
huff_cli/Cargo.toml
huff_cli/README.md
huff_codegen/Cargo.toml
huff_core/Cargo.toml
huff_js/Cargo.toml
huff_lexer/Cargo.toml
huff_parser/Cargo.toml
huff_utils/Cargo.toml
huffup/README.md

Fix: version bumps and contributors

---

huff_codegen/src/irgen/arg_calls.rs
huff_core/tests/macro_invoc_args.rs

fix(cg): fix merge issue 

---

huff_core/tests/push_overrides.rs
huff_parser/src/lib.rs
huff_parser/tests/opcodes.rs
huff_utils/src/ast.rs
huff_utils/src/evm.rs

Adds the `PUSH0` opcode introduced in [EIP-3855](https://eips.ethereum.org/EIPS/eip-3855)

feat: `PUSH0` opcode

---

Cargo.lock

chore(deps): update all deps

---

huff_parser/src/lib.rs
huff_parser/tests/opcodes.rs

fix: rm dbg
